In [42]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [43]:
DATADIR = './PetImages'
CATEGORIES = ["Dog", "Cat"]

In [44]:
for category in CATEGORIES:
    path = os.path.join(DATADIR, category)
    for img in os.listdir(path):
        img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
#         plt.imshow(img_array, cmap="gray")
#         plt.show()

Corrupt JPEG data: 399 extraneous bytes before marker 0xd9
Corrupt JPEG data: 254 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1403 extraneous bytes before marker 0xd9
Corrupt JPEG data: 2230 extraneous bytes before marker 0xd9
Corrupt JPEG data: 226 extraneous bytes before marker 0xd9
Corrupt JPEG data: 65 extraneous bytes before marker 0xd9
Corrupt JPEG data: 162 extraneous bytes before marker 0xd9
Corrupt JPEG data: 128 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1153 extraneous bytes before marker 0xd9
Corrupt JPEG data: 239 extraneous bytes before marker 0xd9
Corrupt JPEG data: 99 extraneous bytes before marker 0xd9
Corrupt JPEG data: 214 extraneous bytes before marker 0xd9


In [45]:
print(img_array)

[[214 214 214 ... 159 163 157]
 [216 216 217 ... 164 166 133]
 [221 221 221 ... 173 183 128]
 ...
 [226 226 231 ...  63  72  69]
 [235 232 230 ...  66  70  66]
 [234 234 229 ...  68  67  70]]


In [46]:
IMG_SIZE = 50
# new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
# plt.imshow(new_array, cmap = 'gray')
# plt.show()

In [47]:
training_data = []
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass
create_training_data()

Corrupt JPEG data: 399 extraneous bytes before marker 0xd9
Corrupt JPEG data: 254 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1403 extraneous bytes before marker 0xd9
Corrupt JPEG data: 2230 extraneous bytes before marker 0xd9
Corrupt JPEG data: 226 extraneous bytes before marker 0xd9
Corrupt JPEG data: 65 extraneous bytes before marker 0xd9
Corrupt JPEG data: 162 extraneous bytes before marker 0xd9
Corrupt JPEG data: 128 extraneous bytes before marker 0xd9
Corrupt JPEG data: 1153 extraneous bytes before marker 0xd9
Corrupt JPEG data: 239 extraneous bytes before marker 0xd9
Corrupt JPEG data: 99 extraneous bytes before marker 0xd9
Corrupt JPEG data: 214 extraneous bytes before marker 0xd9


In [48]:
print(len(training_data))

24946


In [49]:
import random
random.shuffle(training_data)

In [50]:
for sample in training_data[:10]:
    print(sample[1])

0
1
1
0
0
1
0
0
0
0


In [51]:
X = []
y = []

In [52]:
for features, label in training_data:
    X.append(features)
    y.append(label)
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y = np.array(y)

In [53]:
import pickle
pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [54]:
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)

In [55]:
X[1]

array([[[189],
        [189],
        [190],
        ...,
        [150],
        [153],
        [153]],

       [[187],
        [182],
        [168],
        ...,
        [149],
        [152],
        [152]],

       [[177],
        [175],
        [167],
        ...,
        [152],
        [150],
        [153]],

       ...,

       [[195],
        [185],
        [170],
        ...,
        [ 77],
        [ 42],
        [ 71]],

       [[194],
        [189],
        [180],
        ...,
        [ 36],
        [ 29],
        [ 45]],

       [[192],
        [186],
        [178],
        ...,
        [ 54],
        [ 42],
        [ 34]]], dtype=uint8)